
runtime: python39

env_variables:
    REDIS_HOST: your-redis-host
    REDIS_PORT: your-redis-port
    REDIS_PASSWORD: your-redis-password

handlers:
    - url: /static
      static_dir: static/

instance_class: F1
automatic_scaling:
    max_instances: 3